version: '2'
services:
  app:
    container_name: filestash
    build:
        context: https://github.com/abeloris/filestash-onlyoffice.git
        dockerfile: docker/Dockerfile
    restart: always
    environment:
    - APPLICATION_URL=
    - ONLYOFFICE_URL=http://onlyoffice
    - CANARY=true
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver:7.1
    restart: always

volumes:
    filestash: {}
