name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # run only when master branch is updated
  workflow_dispatch:   # allow manual trigger

concurrency:
  group: ${{ github.ref }} # Unique group for each branch
  cancel-in-progress: true # Cancel any in-progress runs for the same group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/filestash:latest